package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataModel implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DataModel() {
    }




}