package com.myspace;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Trade implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String buySellCode;
	private java.lang.String buySideAccountIdentifier;

	private java.lang.String test;

	public Trade() {
	}

	public java.lang.String getBuySellCode() {
		return this.buySellCode;
	}

	public void setBuySellCode(java.lang.String buySellCode) {
		this.buySellCode = buySellCode;
	}

	public java.lang.String getBuySideAccountIdentifier() {
		return this.buySideAccountIdentifier;
	}

	public void setBuySideAccountIdentifier(
			java.lang.String buySideAccountIdentifier) {
		this.buySideAccountIdentifier = buySideAccountIdentifier;
	}

	public java.lang.String getTest() {
		return this.test;
	}

	public void setTest(java.lang.String test) {
		this.test = test;
	}

	public Trade(java.lang.String buySellCode,
			java.lang.String buySideAccountIdentifier, java.lang.String test) {
		this.buySellCode = buySellCode;
		this.buySideAccountIdentifier = buySideAccountIdentifier;
		this.test = test;
	}

}